name: Build Android (APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.gradle
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip \
        build-essential git python3-setuptools python3-wheel \
        libffi-dev libssl-dev libsqlite3-dev zlib1g-dev

    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        pip install buildozer cython

    - name: Build Debug APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: bin/*.apk
